version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "chore(deps):"
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "06:00"
    commit-message:
      prefix: "chore(deps):"
