# https://cloud.google.com/appengine/docs/standard/nodejs/config/appref

runtime: nodejs12
instance_class: F1

automatic_scaling:
  max_instances: 5
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.95
  max_concurrent_requests: 100
  min_pending_latency: 100ms
  max_pending_latency: 1000ms

env_variables:
  NODE_ENV: production

inbound_services:
  - warmup

default_expiration: "3d"

includes:
  - routes.yaml
