# https://cloud.google.com/appengine/docs/standard/nodejs/config/appref

runtime: nodejs12
instance_class: F1

env_variables:
  NODE_ENV: production

inbound_services:
  - warmup

default_expiration: "3d"

includes:
  - routes.yaml
