# https://cloud.google.com/appengine/docs/standard/nodejs/config/appref

runtime: nodejs12
instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1
  max_idle_instances: 1
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
  min_pending_latency: 500ms
  max_pending_latency: 2500ms

entrypoint: node -r source-map-support/register dist/main

env_variables:
  NODE_ENV: production

inbound_services:
  - warmup

default_expiration: "7d"

includes:
  - routes.yaml
