handlers:
  - url: /favicon\.ico
    mime_type: image/x-icon
    static_files: public/favicon.ico
    upload: public/favicon\.ico
    expiration: "7d"

  - url: /((robots|humans)\.txt)$
    static_files: public/\1
    upload: public/(robots|humans)\.txt$
    expiration: "1s"

  - url: /site\.webmanifest
    mime_type: application/json
    static_files: public/site.webmanifest
    upload: public/site\.webmanifest
    expiration: "10m"

  # Web fonts
  - url: /(.*\.eot)$
    mime_type: application/vnd.ms-fontobject
    static_files: public/\1
    upload: public/.*\.eot$

  - url: /(.*\.ttf)$
    mime_type: font/ttf
    static_files: public/\1
    upload: public/.*\.ttf$

  - url: /(.*\.woff)$
    mime_type: font/woff
    static_files: public/\1
    upload: public/.*\.woff$

  - url: /(.*\.woff2)$
    mime_type: font/woff2
    static_files: public/\1
    upload: public/.*\.woff2$

  # Image files
  - url: /(.*\.(png|svg|webp|jpg|jpeg|gif|apng|mp4))$
    static_files: public/\1
    upload: public/.*\.(png|svg|webp|jpg|jpeg|gif|apng|mp4)$

  # Other static files
  - url: /(.*\.(html|css|js|map|xml))$
    static_files: public/\1
    upload: public/.*\.(html|css|js|map|xml)$
    expiration: "10m"

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
