handlers:
  - url: /favicon\.ico
    mime_type: image/x-icon
    static_files: public/favicon.ico
    upload: public/favicon\.ico
    expiration: "7d"

  - url: /robots\.txt
    static_files: public/robots.txt
    upload: public/robots\.txt

  - url: /site\.webmanifest
    static_files: public/site.webmanifest
    upload: public/site\.webmanifest

  # Web fonts
  - url: /(.*\.eot)$
    mime_type: application/vnd.ms-fontobject
    static_files: public/\1
    upload: public/.*\.eot$
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /(.*\.ttf)$
    mime_type: font/ttf
    static_files: public/\1
    upload: public/.*\.ttf$
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /(.*\.woff)$
    mime_type: font/woff
    static_files: public/\1
    upload: public/.*\.woff$
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /(.*\.woff2)$
    mime_type: font/woff2
    static_files: public/\1
    upload: public/.*\.woff2$
    http_headers:
      Access-Control-Allow-Origin: "*"

  # Image files
  - url: /(.*\.(png|svg|webp|jpg|jpeg|gif|apng|mp4))$
    static_files: public/\1
    upload: public/.*\.(png|svg|webp|jpg|jpeg|gif|apng|mp4)$
    http_headers:
      Access-Control-Allow-Origin: "*"

  # Static index page
  - url: /
    secure: always
    redirect_http_response_code: 301
    static_files: public/index.html
    upload: public/index.html
    http_headers:
      Strict-Transport-Security: max-age=63072000; includeSubDomains; preload

  # Other static files
  - url: /(.*\.(html|css|js|map|xml))$
    static_files: public/\1
    upload: public/.*\.(html|css|js|map|xml)$
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /ping
    secure: always
    redirect_http_response_code: 301
    script: auto
