name: Auto Merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'app-engine'
      - 'CodeQL'

jobs:
  merge-me:
    # It is often a desired behavior to merge only when a workflow execution
    # succeeds. This can be changed as needed.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: SQUASH
          PRESET: DEPENDABOT_MINOR
          ENABLED_FOR_MANUAL_CHANGES: 'true'
