name: gcloud-cleanup

env:
  GCLOUD_PROJECT_ID: kvaapagarrot

on:
  schedule:
    # At 00:00 every Sunday
    - cron:  '0 0 * * 0'

jobs:

  clean-up:
    name: Clean-up old artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Import Service Account key
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 -d > /tmp/auth.json

      - name: GCloud Auth
        run: |
          gcloud --quiet auth \
          activate-service-account "${{ secrets.GCP_SA_EMAIL }}" \
          --key-file=/tmp/auth.json \
          --project="${GCLOUD_PROJECT_ID}"

      # Get versions without traffic, sort by last deployed desc
      # Skip output header along with two last deployed versions (=3 lines skip)
      # Delete remaining
      - name: Delete old versions
        run: |
          LIST=($(gcloud app versions list --service=default --sort-by="~LAST_DEPLOYED" --filter="TRAFFIC_SPLIT=0" | awk '{ print $2 }' | tail -n +4))
          echo Versions for deletion:
          printf "%s\n" $LIST
          gcloud --quiet app versions delete --service=default $LIST
